### ISSUE TITLE
bibtex reference

### ISSUE THREAD

**Issue by AngledLuffa** [musixmatchresearch/umberto#10]
Would you add a bibtex reference for your model (if there is one) to either this repo or to huggingface?  I used it to build a constituency parser for Italian, and I would like to give proper credit for the transformer.

Thanks!

**Comment by AngledLuffa** [comment]
Temporarily I have cited the data source, as it was the only thing I found in the README.  This seems kind of jarring in a list of transformer citations: 2018, 2019, 2020, 2020, 2020, *2006*

**Comment by loretoparisi** [comment]
> Temporarily I have cited the data source, as it was the only thing I found in the README.  This seems kind of jarring in a list of transformer citations: 2018, 2019, 2020, 2020, 2020, *2006*

Thank you very much! We are preparing the reference.

**Comment by paulthemagno** [comment]
Hey @AngledLuffa, sorry for the late response.

If you want to cite this work, you can use this bibtex:
```bibtex
@misc{musixmatch-2020-umberto,
  author = {Loreto Parisi and Simone Francia and Paolo Magnani},
  title = {UmBERTo: an Italian Language Model trained with Whole Word Masking},
  year = {2020},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/musixmatchresearch/umberto}}
}
```

Thank you!! 😊

**Comment by AngledLuffa** [comment]
Great, thanks!
