### ISSUE TITLE
Model fine-tuning Example

### ISSUE THREAD

**Issue by loretoparisi** [musixmatchresearch/umberto#5]
Add a new example of umBERTo [model fine-tuning](https://huggingface.co/transformers/v2.0.0/examples.html#language-model-fine-tuning) on a specific text domain. For this example we will use a poetry textual domain, like the one attached here (Dante Alighieri, La Divina Commedia)
[dante.txt](https://github.com/musixmatchresearch/umberto/files/5108548/dante.txt)

**Comment by paulthemagno** [comment]
To make your model be more comfortable to understand a **specific text domain**, like _poetry_, you can use **Hugging Face** [run_language_modeling.py](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_language_modeling.py).

Make sure to have a train dataset and test dataset, so you can split your dataset as you prefer (like 70% train - 30% test). In this case the dataset doesn't contain labels, so you have not to check measures like accuracy or Fscore. You could rather check if _perplexity_ or _loss_ is decreasing.

This script uses [Trainer class](https://huggingface.co/transformers/main_classes/trainer.html#transformers.Trainer) which takes [training args](https://huggingface.co/transformers/main_classes/trainer.html#transformers.TrainingArguments) directly from the args given to [run_language_modeling.py](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_language_modeling.py) script. So if you want to add training arguments like `per_device_train_batch_size`, `num_train_epochs` and so on, take a look at [this](https://huggingface.co/transformers/main_classes/trainer.html#transformers.TrainingArguments) and add those args to the script below.

```bash
export TRAIN_FILE=/path/to/dante_train.txt
export TEST_FILE=/path/to/dante_test.txt

python run_language_modeling.py \
    --output_dir=output \
    --model_type=camembert \
    --model_name_or_path=Musixmatch/umberto-commoncrawl-cased-v1 \
    --do_train \
    --train_data_file=$TRAIN_FILE \
    --do_eval \
    --eval_data_file=$TEST_FILE \
    --mlm
```

You can change `--model_name_or_path` using  both 

- `Musixmatch/umberto-commoncrawl-cased-v1`

- and `Musixmatch/umberto-wikipedia-uncased-v1`.
If you use `Musixmatch/umberto-wikipedia-uncased-v1`, the only caution is to change [run_language_modeling.py](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_language_modeling.py) to add the `lower_case` argument, being this model an uncased model. To do it, go to this [line](https://github.com/huggingface/transformers/blob/0fab39695af714d70a92381b6d9f4f99674c9d9c/examples/language-modeling/run_language_modeling.py#L204) and add `do_lower_case=True`, like: 

```python
...
if model_args.tokenizer_name:
        tokenizer = AutoTokenizer.from_pretrained(model_args.tokenizer_name, do_lower_case=True, cache_dir=model_args.cache_dir)
    elif model_args.model_name_or_path:
        tokenizer = AutoTokenizer.from_pretrained(model_args.model_name_or_path, do_lower_case=True, cache_dir=model_args.cache_dir)
    else:
        raise ValueError(
            "You are instantiating a new tokenizer from scratch. This is not supported, but you can do it from another script, save it,"
            "and load it from here, using --tokenizer_name"
        )
...
