### ISSUE TITLE
Publish finetuned pos model on huggingface

### ISSUE THREAD

**Issue by sachaarbonel** [musixmatchresearch/umberto#6]
Hi, thank's for this great model. I see in the readme you cite the great result you got on the downstreak POS task but I don't see it on huggingface. Would it be possible to upload the finetuned pos model on huggingface ? I'd like to take advantage of their (newish released) REST inference api

**Comment by loretoparisi** [comment]
@sachaarbonel thanks for the suggestion, we will look at this!
